# Generated by Django 5.2.5 on 2025-08-11 15:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_servicio', models.CharField(choices=[('desarrollo', 'Desarrollo de Software'), ('mantenimiento', 'Mantenimiento'), ('consultoria', 'Consultoría'), ('capacitacion', 'Capacitación'), ('otro', 'Otro')], default='desarrollo', max_length=20)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa por hora (USD)')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipo_servicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=20, unique=True, verbose_name='Número de cotización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('modalidad_pago', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unico', 'Pago único')], default='unico', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento (USD)')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='IVA (%)')),
                ('iva_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA (USD)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('terminos_condiciones', models.TextField(blank=True, verbose_name='Términos y condiciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Horas estimadas')),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa por hora (USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
            },
        ),
    ]
